### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by koenr** [moodlehq/moodle-tool_migratehvp2h5p#6] opened 2020-08-12 15:11 UTC
One migration failed with the following error:

Error migration hvp activity with id 35: Coding error detected, it must be fixed by a programmer: moodle_database::update_record_raw() id field must be specified.ied.

I'm adding the mdl_hvp table here as an sql export, containing the one remaining activity that does not want to migrate because of the error above.

[mdl_hvp.txt](https://github.com/moodlehq/moodle-tool_migratehvp2h5p/files/5063642/mdl_hvp.txt)

**Comment by merrill-oakland** [comment] 2020-08-13 21:53
Does the particular activity have a max grade of 0 by chance? I opened #7, which shows a similar error.

**Comment by koenr** [comment] 2020-08-13 22:26
Yes.
I changed it to 1 and the migration succeeded. Thanks a million!

**Comment by koenr** [comment] 2020-08-13 22:30
Ah, you can't have a 0 in the new h5p_activity module. I tried to revert to 0 after the migration and the value should be between 1 and 100.

**Comment by sarjona** [comment] 2020-12-02 14:13
Hi  @koenr!!
Thanks for reporting this! Although this issue was created before, I'm going to close it as a duplicate because the information in  #7 the issue Eric mentioned is clearer to reproduce it :-)

**Closed by sarjona** 2020-12-02 14:13 UTC
Labels: duplicate

**Comment by koenr** [comment] 2020-12-02 16:08
Sure @sarjona  - thank you for working on this. Seems like a fine solution.
