### ISSUE TITLE
Error at migrating mod_hvp activity to mod_h5pactivity

### ISSUE THREAD

**Issue by franszwijnenberg** [moodlehq/moodle-tool_migratehvp2h5p#15] opened 2020-12-04 10:22 UTC
using: 
Moodle LMS 3.9.3 (Build: 20201109)
mod_hvp build: 2020080400
Last update H5P dec. 1ste 2020
HVP activity Fill in the Blanks (1.12.8)
![image](https://user-images.githubusercontent.com/75476440/101151336-c9a84180-3621-11eb-88e4-1131ccbb81c4.png)
setting:
hide original activty:
![image](https://user-images.githubusercontent.com/75476440/101151439-f197a500-3621-11eb-8d69-02dfa4b8c4fb.png)
error at migrating hvp-activity with ID 14258
![image](https://user-images.githubusercontent.com/75476440/101151571-24da3400-3622-11eb-8e54-6ed2ec501039.png)

**Comment by sarjona** [comment] 2020-12-04 11:51
Hi Frans!
Thanks for reporting this issue. However, I can't reproduce the error with the information you've given (I've been able to restore as expected a "Fill in the blanks" activity downloaded from https://h5p.org/fill-in-the-blanks with some attempts):

![Screenshot from 2020-12-04 12-49-15](https://user-images.githubusercontent.com/900389/101160424-4b529c00-362f-11eb-9379-567dcff8b9f0.png)

Could you please add more information to the issue? If we can't reproduce it, it's really hard to find where the error is. Besides, it will be great if you could temporary enable Debugging level to development and send the whole stack trace.
Thanks in advance!

**Comment by franszwijnenberg** [comment] 2020-12-07 15:06
Hi Sara,

I send you an Email.

KInd Regards

Frans Zwijnenberg
Avetica

**Comment by sarjona** [comment] 2021-01-08 09:33
I'm going to close this issue because we confirmed with Frans that it was fixed in the most recent versions of the tool :-)

**Closed by sarjona** 2021-01-08 09:33 UTC
Labels: question

**Comment by adpe** [comment] 2021-01-29 09:11
Hi @sarjona 

I face right now the same problem. But it is on a development environment. On my local Moodle environment (dockerized) with the same versions it's working.

- Moodle 3.9.4 (Build: 20210118)
- mod_hvp 1.21.0 (Build: 2020080400)
- mod_h5pactivity (Build: 2020061500)
- tool_migratehvp2h5p 0.1.3 (Build: 2020121100)

Do you have any idea?

Greets
Adrian
